/**
 * Generates the source for an illustrative custom OpenZeppelin smart-account
 * policy in Rust — `FrequencyLimitPolicy` — parameterised by the synthesized
 * window and call cap.
 *
 * The generated code models the real OZ `Policy` trait shape (associated
 * `AccountParams`, plus `install` / `enforce` / `uninstall`, with `enforce`
 * rejecting by panicking). It is intentionally simple and is emitted only as a
 * starting point. See {@link ILLUSTRATIVE_HEADER}: it is NOT audited and NOT
 * deploy-ready.
 */

import type { FrequencyLimitPolicy } from './types.js';

/** Header stamped on every generated Rust file. Do not weaken this wording. */
export const ILLUSTRATIVE_HEADER = `// =============================================================================
//  ILLUSTRATIVE / UNAUDITED — NOT DEPLOY-READY
//
//  This file was generated by policywright as a *starting point* for a custom
//  OpenZeppelin Stellar smart-account policy. It has NOT been audited, NOT been
//  tested on-chain, and MUST NOT be deployed as-is. It models the OZ \`Policy\`
//  trait shape so a developer can adapt it; treat every line as a draft.
// =============================================================================`;

/**
 * Render the Rust source for a `FrequencyLimitPolicy` with the given limits
 * baked in as documented defaults.
 */
export function renderFrequencyLimitPolicy(policy: FrequencyLimitPolicy): string {
  const { windowSecs, maxCalls } = policy;
  return `${ILLUSTRATIVE_HEADER}
#![no_std]

//! A custom policy that bounds how often the scoped calls may run within a
//! rolling time window. Synthesized defaults: at most ${maxCalls} call(s) per
//! ${windowSecs} second(s).
//!
//! NOTE: OpenZeppelin's \`Policy\` trait is \`install\` / \`enforce\` / \`uninstall\`.
//! There is no \`can_enforce\` hook; validation and state mutation both happen in
//! \`enforce\`, which rejects by panicking.

use soroban_sdk::{
    auth::Context, contract, contracterror, contractimpl, contracttype, Address, Env, Vec,
};
use stellar_accounts::policies::Policy;
use stellar_accounts::smart_account::{ContextRule, Signer};

/// Install-time parameters for the policy (the trait's associated \`AccountParams\`).
#[contracttype]
#[derive(Clone)]
pub struct FrequencyLimitParams {
    /// Length of the rolling window, in seconds.
    pub window_secs: u64,
    /// Maximum number of enforcements allowed within the window.
    pub max_calls: u32,
}

/// Synthesized defaults, surfaced for reference. Real installs pass params at
/// \`add_policy\` time; these mirror what policywright observed.
pub const DEFAULT_WINDOW_SECS: u64 = ${windowSecs};
pub const DEFAULT_MAX_CALLS: u32 = ${maxCalls};

#[contracttype]
enum DataKey {
    /// Per (smart account, context rule) install parameters.
    Params(Address, u32),
    /// Per (smart account, context rule) timestamps of recent enforcements.
    Calls(Address, u32),
}

#[contracterror]
#[derive(Copy, Clone, PartialEq, Eq)]
pub enum FrequencyError {
    NotInstalled = 1,
    RateExceeded = 2,
}

#[contract]
pub struct FrequencyLimitPolicy;

#[contractimpl]
impl Policy for FrequencyLimitPolicy {
    type AccountParams = FrequencyLimitParams;

    /// Persist the limit for this (smart account, context rule) pair.
    fn install(
        e: &Env,
        install_params: Self::AccountParams,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        e.storage().persistent().set(
            &DataKey::Params(smart_account.clone(), context_rule.id),
            &install_params,
        );
        e.storage().persistent().set(
            &DataKey::Calls(smart_account, context_rule.id),
            &Vec::<u64>::new(e),
        );
    }

    /// Count enforcements in the trailing window; record this one or panic.
    fn enforce(
        e: &Env,
        _context: Context,
        _authenticated_signers: Vec<Signer>,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        let params: FrequencyLimitParams = e
            .storage()
            .persistent()
            .get(&DataKey::Params(smart_account.clone(), context_rule.id))
            .unwrap_or_else(|| panic_with_error!(e, FrequencyError::NotInstalled));

        let now = e.ledger().timestamp();
        let window_start = now.saturating_sub(params.window_secs);

        let key = DataKey::Calls(smart_account, context_rule.id);
        let recent: Vec<u64> = e.storage().persistent().get(&key).unwrap_or(Vec::new(e));

        // Keep only timestamps inside the trailing window.
        let mut kept: Vec<u64> = Vec::new(e);
        for ts in recent.iter() {
            if ts >= window_start {
                kept.push_back(ts);
            }
        }

        if kept.len() >= params.max_calls {
            panic_with_error!(e, FrequencyError::RateExceeded);
        }

        kept.push_back(now);
        e.storage().persistent().set(&key, &kept);
    }

    /// Drop persisted state when the policy is removed from the rule.
    fn uninstall(e: &Env, context_rule: ContextRule, smart_account: Address) {
        e.storage()
            .persistent()
            .remove(&DataKey::Params(smart_account.clone(), context_rule.id));
        e.storage()
            .persistent()
            .remove(&DataKey::Calls(smart_account, context_rule.id));
    }
}

use soroban_sdk::panic_with_error;
`;
}
