/**
 * Generates the source for the policywright custom OpenZeppelin smart-account
 * policy in Rust — `FrequencyLimitPolicy` — parameterised by the synthesized
 * window and call cap.
 *
 * The rendered output is byte-identical to the compiled-and-tested crate at
 * contracts/frequency-limit-policy/src/lib.rs (with the synthesized defaults
 * substituted in): the reconciled template implements the real OZ `Policy`
 * trait from stellar-accounts v0.7.2 — `install` / `enforce` / `uninstall`
 * with an associated `AccountParams` type, storage keyed
 * `AccountContext(smart_account, context_rule_id)`, `AlreadyInstalled` and
 * panic-if-not-installed guards, and the stock TTL constants. Equality with
 * the crate source is locked by test/rust-policy.test.ts.
 *
 * See {@link ILLUSTRATIVE_HEADER}: the output is NOT audited and NOT for
 * production deployment.
 */

import type { FrequencyLimitPolicy } from './types.js';

/** Header stamped on every generated Rust file. Do not weaken this wording. */
export const ILLUSTRATIVE_HEADER = `// =============================================================================
//  ILLUSTRATIVE / UNAUDITED — NOT DEPLOY-READY
//
//  Generated contracts are illustrative and unaudited — not for production
//  deployment until the Audit Bank audit.
//
//  This file was generated by policywright as a *starting point* for a custom
//  OpenZeppelin Stellar smart-account policy. It compiles and its unit tests
//  run against the real OZ \`Policy\` trait (stellar-accounts v0.7.2), and
//  policywright deploys instances to TESTNET only. It has NOT been audited
//  and MUST NOT be deployed to mainnet or used to guard real value.
// =============================================================================`;

/**
 * Render the Rust source for a `FrequencyLimitPolicy` with the given limits
 * baked in as documented defaults.
 */
export function renderFrequencyLimitPolicy(policy: FrequencyLimitPolicy): string {
  const { windowSecs, maxCalls } = policy;
  return `${ILLUSTRATIVE_HEADER}
#![no_std]

//! # Frequency Limit Policy
//!
//! Bounds how often the scoped calls may run within a rolling wall-clock
//! window: at most \`max_calls\` enforcements per \`window_secs\` seconds.
//! Synthesized defaults observed by policywright: at most ${maxCalls} call(s) per
//! ${windowSecs} second(s).
//!
//! Implements the OpenZeppelin \`stellar-accounts\` v0.7.2 \`Policy\` trait —
//! \`install\` / \`enforce\` / \`uninstall\` with an associated \`AccountParams\`
//! type. There is no \`can_enforce\` hook; validation and state mutation both
//! happen in \`enforce\`, which rejects by panicking.
//!
//! Storage follows the stock-policy pattern: all state lives under
//! \`FrequencyLimitStorageKey::AccountContext(smart_account, context_rule_id)\`
//! in persistent storage, so state is segregated per (smart account, context
//! rule) pair and one deployment serves many accounts.
//!
//! The window is measured in wall-clock seconds (\`e.ledger().timestamp()\`),
//! deliberately unlike the stock \`spending_limit\`, whose window is measured
//! in ledgers — a call-frequency bound is a human-time constraint. The
//! emitted \`context-rule.json\` states this unit in its install params.
//!
//! Unlike the stock \`spending_limit\`, \`enforce\` does not require a non-empty
//! \`authenticated_signers\` list: frequency limiting meters calls, not
//! signers, and policy-only context rules must stay usable.
//!
//! Uninstalling drops the stored params and call history, so a subsequent
//! reinstall starts a fresh window — the smart account governs its own
//! policy set, exactly as in the stock lifecycle.

use soroban_sdk::{
    auth::Context, contract, contracterror, contractevent, contractimpl, contracttype,
    panic_with_error, Address, Env, Vec,
};
use stellar_accounts::{
    policies::Policy,
    smart_account::{ContextRule, Signer},
};

/// Event emitted when a frequency limit policy is enforced.
#[contractevent]
#[derive(Clone)]
pub struct FrequencyLimitEnforced {
    #[topic]
    pub smart_account: Address,
    pub context: Context,
    pub context_rule_id: u32,
    pub calls_in_window: u32,
}

/// Event emitted when a frequency limit policy is installed.
#[contractevent]
#[derive(Clone, Debug)]
pub struct FrequencyLimitInstalled {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
    pub window_secs: u64,
    pub max_calls: u32,
}

/// Event emitted when a frequency limit policy is uninstalled.
#[contractevent]
#[derive(Clone, Debug)]
pub struct FrequencyLimitUninstalled {
    #[topic]
    pub smart_account: Address,
    pub context_rule_id: u32,
}

/// Installation parameters for the frequency limit policy (the trait's
/// associated \`AccountParams\`).
#[contracttype]
#[derive(Clone, Debug, PartialEq)]
pub struct FrequencyLimitParams {
    /// Length of the rolling window, in seconds.
    pub window_secs: u64,
    /// Maximum number of enforcements allowed within the window.
    pub max_calls: u32,
}

/// Internal storage structure for frequency tracking.
#[contracttype]
#[derive(Clone, Debug, PartialEq)]
pub struct FrequencyLimitData {
    /// Length of the rolling window, in seconds.
    pub window_secs: u64,
    /// Maximum number of enforcements allowed within the window.
    pub max_calls: u32,
    /// Ledger timestamps (Unix seconds) of the enforcements in the window.
    pub call_history: Vec<u64>,
}

/// Error codes for frequency limit policy operations.
///
/// The stock policies claim 3200 (simple threshold), 3210 (weighted
/// threshold), and 3220 (spending limit); this policy claims 3230.
#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
#[repr(u32)]
pub enum FrequencyLimitError {
    /// The policy is not installed for this (smart account, context rule).
    SmartAccountNotInstalled = 3230,
    /// The call would exceed \`max_calls\` within the rolling window.
    CallLimitExceeded = 3231,
    /// \`window_secs\` and \`max_calls\` must both be positive, and \`max_calls\`
    /// must not exceed \`MAX_HISTORY_ENTRIES\`.
    InvalidWindowOrLimit = 3232,
    /// The policy is already installed for this (smart account, context
    /// rule).
    AlreadyInstalled = 3233,
}

/// Storage key for the frequency limit policy, segregated per
/// (smart account, context rule id) exactly like the stock policies.
#[contracttype]
pub enum FrequencyLimitStorageKey {
    /// Storage key for frequency limit data of a smart account context rule.
    AccountContext(Address, u32),
}

const DAY_IN_LEDGERS: u32 = 17280;
/// TTL extension applied when the stored entry is read: ~30 days.
pub const FREQUENCY_LIMIT_EXTEND_AMOUNT: u32 = 30 * DAY_IN_LEDGERS;
/// Remaining-TTL threshold under which the extension applies: ~29 days.
pub const FREQUENCY_LIMIT_TTL_THRESHOLD: u32 = FREQUENCY_LIMIT_EXTEND_AMOUNT - DAY_IN_LEDGERS;
/// Upper bound on \`max_calls\`, enforced at install. The call history holds at
/// most \`max_calls\` entries, so this bounds the stored entry's size and
/// prevents storage DoS. (The stock \`spending_limit\` enforces its identical
/// cap at enforce time instead, because its history is not bounded by its
/// limit params; here the install-time check makes an undeliverable
/// configuration impossible.)
pub const MAX_HISTORY_ENTRIES: u32 = 1000;

/// Synthesized defaults, surfaced for reference. Real installs pass params at
/// \`add_context_rule\` / \`add_policy\` time; these mirror what policywright
/// observed.
pub const DEFAULT_WINDOW_SECS: u64 = ${windowSecs};
/// See [\`DEFAULT_WINDOW_SECS\`].
pub const DEFAULT_MAX_CALLS: u32 = ${maxCalls};

#[contract]
pub struct FrequencyLimitPolicy;

#[contractimpl]
impl Policy for FrequencyLimitPolicy {
    type AccountParams = FrequencyLimitParams;

    /// Count the enforcements inside the trailing window; record this one or
    /// panic. Requires authorization from the smart account.
    fn enforce(
        e: &Env,
        context: Context,
        _authenticated_signers: Vec<Signer>,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        smart_account.require_auth();

        let key = FrequencyLimitStorageKey::AccountContext(smart_account.clone(), context_rule.id);
        let mut data = get_data(e, context_rule.id, &smart_account);
        let now = e.ledger().timestamp();

        // Exclusive window start: entries at or before \`now - window_secs\`
        // are evicted, the stock spending_limit eviction rule for any
        // realistic clock. At the genesis edge (\`now < window_secs\`) this
        // deliberately diverges fail-closed: stock clamps the cutoff to zero
        // and evicts an entry at exactly 0, while here nothing is evicted at
        // all — strictly more restrictive, unreachable with real ledger
        // close times.
        let cutoff = now.checked_sub(data.window_secs);
        let mut kept: Vec<u64> = Vec::new(e);
        for ts in data.call_history.iter() {
            if cutoff.is_none_or(|c| ts > c) {
                kept.push_back(ts);
            }
        }

        if kept.len() >= data.max_calls {
            panic_with_error!(e, FrequencyLimitError::CallLimitExceeded)
        }

        kept.push_back(now);
        data.call_history = kept;
        e.storage().persistent().set(&key, &data);

        FrequencyLimitEnforced {
            smart_account,
            context,
            context_rule_id: context_rule.id,
            calls_in_window: data.call_history.len(),
        }
        .publish(e);
    }

    /// Persist the limit for this (smart account, context rule) pair. Panics
    /// if the policy is already installed or the params are invalid. Requires
    /// authorization from the smart account.
    fn install(
        e: &Env,
        install_params: Self::AccountParams,
        context_rule: ContextRule,
        smart_account: Address,
    ) {
        smart_account.require_auth();

        if install_params.window_secs == 0
            || install_params.max_calls == 0
            || install_params.max_calls > MAX_HISTORY_ENTRIES
        {
            panic_with_error!(e, FrequencyLimitError::InvalidWindowOrLimit)
        }

        let key = FrequencyLimitStorageKey::AccountContext(smart_account.clone(), context_rule.id);
        if e.storage().persistent().has(&key) {
            panic_with_error!(e, FrequencyLimitError::AlreadyInstalled)
        }

        let data = FrequencyLimitData {
            window_secs: install_params.window_secs,
            max_calls: install_params.max_calls,
            call_history: Vec::new(e),
        };
        e.storage().persistent().set(&key, &data);

        FrequencyLimitInstalled {
            smart_account,
            context_rule_id: context_rule.id,
            window_secs: install_params.window_secs,
            max_calls: install_params.max_calls,
        }
        .publish(e);
    }

    /// Drop persisted state when the policy is removed from the rule. Panics
    /// if the policy is not installed. Requires authorization from the smart
    /// account.
    fn uninstall(e: &Env, context_rule: ContextRule, smart_account: Address) {
        smart_account.require_auth();

        let key = FrequencyLimitStorageKey::AccountContext(smart_account.clone(), context_rule.id);
        if !e.storage().persistent().has(&key) {
            panic_with_error!(e, FrequencyLimitError::SmartAccountNotInstalled)
        }
        e.storage().persistent().remove(&key);

        FrequencyLimitUninstalled {
            smart_account,
            context_rule_id: context_rule.id,
        }
        .publish(e);
    }
}

#[contractimpl]
impl FrequencyLimitPolicy {
    /// Retrieve the frequency limit data for a (smart account, context rule)
    /// pair, extending the entry's TTL like the stock policies do. Panics if
    /// the policy is not installed.
    pub fn get_frequency_limit_data(
        e: Env,
        context_rule_id: u32,
        smart_account: Address,
    ) -> FrequencyLimitData {
        get_data(&e, context_rule_id, &smart_account)
    }
}

/// Read the stored data, extending its TTL — the stock-policy access pattern.
fn get_data(e: &Env, context_rule_id: u32, smart_account: &Address) -> FrequencyLimitData {
    let key = FrequencyLimitStorageKey::AccountContext(smart_account.clone(), context_rule_id);
    e.storage()
        .persistent()
        .get(&key)
        .inspect(|_| {
            e.storage().persistent().extend_ttl(
                &key,
                FREQUENCY_LIMIT_TTL_THRESHOLD,
                FREQUENCY_LIMIT_EXTEND_AMOUNT,
            );
        })
        .unwrap_or_else(|| panic_with_error!(e, FrequencyLimitError::SmartAccountNotInstalled))
}
`;
}
